
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Renan
 */
public class IMC extends javax.swing.JFrame {

    /**
     * Creates new form IMC
     */
    public IMC() {
        initComponents();
        //Define o tamanho do Frame
        setSize(745,505);
        setLocationRelativeTo(null);
        //Define o tamanho do frame fixo
        setResizable(false); 
        //Titulo da Janela
        this.setTitle("Calculo de IMC");
        //ICONE DO JANELA
        URL caminhoImage = getClass().getResource("/imagens/balanca.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoImage);
        this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGsexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTaltura = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTimc = new javax.swing.JTextField();
        jBcalcular = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLtexto = new javax.swing.JLabel();
        jLtexto1 = new javax.swing.JLabel();
        jBlimpar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTpeso = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jBminimiza = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBfechar1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Campo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setText("Altura:");

        jTaltura.setText("Ex: 1.70");
        jTaltura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTalturaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTalturaFocusLost(evt);
            }
        });
        jTaltura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTalturaMouseReleased(evt);
            }
        });
        jTaltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTalturaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel5.setText("Peso:");

        jTimc.setEnabled(false);

        jBcalcular.setText("Calcular");
        jBcalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcalcularActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLtexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLtexto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLtexto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLtexto1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jBlimpar.setText("Limpar");
        jBlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlimparActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel6.setText("IMC:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTimc, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTpeso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTaltura, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBlimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBcalcular))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTaltura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTpeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBlimpar))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTimc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBcalcular)))
                .addGap(27, 27, 27)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jLabel3.setText("Calculo de Massa Corporal (IMC)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3))
                .addGap(0, 16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 30, 400, 410);

        jBminimiza.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBminimiza.setText("Tabela");
        jBminimiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBminimizaActionPerformed(evt);
            }
        });
        getContentPane().add(jBminimiza);
        jBminimiza.setBounds(440, 30, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/medica.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(430, 190, 300, 310);

        jBfechar1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBfechar1.setText("Desenvolvedor");
        jBfechar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBfechar1ActionPerformed(evt);
            }
        });
        getContentPane().add(jBfechar1);
        jBfechar1.setBounds(440, 80, 120, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lousa.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-30, 0, 770, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlimparActionPerformed
        // TODO add your handling code here:
        jTaltura.setText("");
        jTpeso.setText("");
        jTimc.setText("");
        jLtexto.setText("");
        jLtexto1.setText("");
        
        jTimc.disable();
        
    }//GEN-LAST:event_jBlimparActionPerformed

    private void jBcalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcalcularActionPerformed
        // TODO add your handling code here:
        float peso,altura,r;
        String campo = " ";
        peso = Float.valueOf(jTpeso.getText());
        altura = Float.valueOf(jTaltura.getText());
        r = peso/(altura*altura);
        //jTresultado.setText(String.valueOf(r));
        
        if(r >=13.5 && r<= 17){
          jLtexto.setText(String.valueOf("Seu Indice de Massa Corporal " ));
          jLtexto1.setText(String.valueOf("Está Muito Abaixo do Peso "));
          jTimc.setText(String.valueOf(r));
        }else if (r >= 17 && r<= 18.49){
          jLtexto.setText(String.valueOf("Seu Indice de Massa Corporal "));
          jLtexto1.setText(String.valueOf("Está Abaixo do Peso "));
          jTimc.setText(String.valueOf(r));
        }else if(r >=18.5 && r<= 24.99){
          jLtexto.setText(String.valueOf("Seu Indice de Massa Corporal "));
          jLtexto1.setText(String.valueOf("Seu Peso está Normal "));
          jTimc.setText(String.valueOf(r));
        }else if(r>=25 && r<=29.99){
          jLtexto.setText(String.valueOf("Seu Indice de Massa Corporal "));
          jLtexto1.setText(String.valueOf("Você está Acima do Peso "));
          jTimc.setText(String.valueOf(r));
        }else if(r>= 30 && r<=34.99){
         jLtexto.setText(String.valueOf("Seu Indice de Massa Corporal "));
         jLtexto1.setText(String.valueOf("Você está Com Obesidade (Moderada) "));
         jTimc.setText(String.valueOf(r));
        }else if(r>=35 && r<=39.99){
         jLtexto.setText(String.valueOf("Seu Indice de Massa Corporal "));
         jLtexto1.setText(String.valueOf("Você está Com Obesidade (Severa) "));
         jTimc.setText(String.valueOf(r));
        }else if(r >= 40){
         jLtexto.setText(String.valueOf("Seu Indice de Massa Corporal "));
         jLtexto1.setText(String.valueOf("Você está Com Obesidade (Morbida)"));
         jTimc.setText(String.valueOf(r));
        }else{
         jLtexto.setText(String.valueOf("Valor Indisponivel para Calculo"));
         jLtexto1.setText(String.valueOf(""));
         jTimc.setText(String.valueOf(r));
        }
        jTimc.enable();
        
    }//GEN-LAST:event_jBcalcularActionPerformed

    private void jBminimizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBminimizaActionPerformed
    new janela2().setVisible(true);
    }//GEN-LAST:event_jBminimizaActionPerformed

    private void jBfechar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBfechar1ActionPerformed
        // TODO add your handling code here:
        new Desenvolvedor().setVisible(true);
    }//GEN-LAST:event_jBfechar1ActionPerformed

    private void jTalturaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTalturaMouseReleased
        // TODO add your handling code here:
        //este evento apaga oque estiver no campo quando for selecionado
        jTaltura.setText("");
    }//GEN-LAST:event_jTalturaMouseReleased

    private void jTalturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTalturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTalturaActionPerformed

    private void jTalturaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTalturaFocusGained
        // TODO add your handling code here:      

    }//GEN-LAST:event_jTalturaFocusGained

    private void jTalturaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTalturaFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTalturaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IMC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGsexo;
    private javax.swing.JButton jBcalcular;
    private javax.swing.JButton jBfechar1;
    private javax.swing.JButton jBlimpar;
    private javax.swing.JButton jBminimiza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLtexto;
    private javax.swing.JLabel jLtexto1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTaltura;
    private javax.swing.JTextField jTimc;
    private javax.swing.JTextField jTpeso;
    // End of variables declaration//GEN-END:variables
}
